import type { Metadata } from "next";
import { Header,QueryClientProviderWrapper ,ToastProvider} from "@/src/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="p-4">
        <QueryClientProviderWrapper>
        <>
          <ToastProvider /> 
          {children}
        </>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
