import type { Metadata } from "next";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { QueryClientProviderWrapper } from "@/src/components";
import { ToastProvider } from "@/src/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviderWrapper>
        <ReactQueryDevtools position="bottom"/>
        <> 
          <ToastProvider /> 
          {children}
        </>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
